"""
v6: Fully separated Yes/No pipelines with per-class diversity filtering.

Changes from v5:
- Yes and No generated by independent prompts tuned to each class
- Each batch produces only one class (all Yes or all No)
- Diversity and distribution filters run per-class — no cross-class contamination
- Filters applied to the full growing pool (pool + new candidates) each iteration,
  not just to the incoming batch — the pool is reselected from scratch each time
- Output is 50/50 balanced (TARGET_N/2 Yes + TARGET_N/2 No)
- Both classes generated concurrently

Usage:
    python v6_generate.py               # full run to TARGET_N
    python v6_generate.py --dry-run     # single iteration, small target
"""
import argparse
import asyncio
import csv
import json
import random
import re
from pathlib import Path

import litellm
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

litellm.api_key = Path(__file__).parent.parent / "secrets" / "openai_api_key.txt"
litellm.api_key = litellm.api_key.read_text().strip()

# ── Config ────────────────────────────────────────────────────────────────────
REAL_DATA_PATH = (
    Path(__file__).parent.parent.parent
    / "data" / "CT24_checkworthy_english" / "CT24_checkworthy_english_train.csv"
)
OUTPUT_FILE = Path(__file__).parent / "v6_samples.csv"

TARGET_N         = 8192   # total samples; split evenly between classes
OVERSHOOT_FACTOR = 2.0   # accumulate this many × target before filtering each iteration
BATCH_SIZE       = 8    # sentences per API call (all same class)
NUM_WORKERS      = 15    # concurrent API calls across both classes combined
N_ITERATIONS     = 4     # number of generate → filter cycles

FEW_SHOT_N            = 4    # real same-class examples shown per batch prompt
FEW_SHOT_REFERENCE_N  = 32  # pool size per class for few-shot sampling
REFERENCE_N           = 32  # held-out real examples per class for distribution scoring

TOPICS = [
    "healthcare", "tax policy", "the economy", "employment", "education",
    "energy", "crime", "the military", "trade", "reproductive rights",
    "gun control", "the environment", "climate change", "vaccines",
    "elections", "immigration", "foreign policy", "social security",
    "infrastructure", "housing",
]

# ── Prompts ───────────────────────────────────────────────────────────────────
SYSTEM_YES = """\
You are generating training data for a political fact-checking research project.
Generate CHECKWORTHY sentences in the style of US presidential or congressional debate transcripts.

A checkworthy sentence makes a SPECIFIC VERIFIABLE CLAIM:
- Specific numbers or statistics
- Claims about someone's past votes, positions, or actions (even brief: "He was for the invasion of Iraq.")
- Claims about one's own record ("I've appointed more judges than any president before me.")
- Directional facts with a named subject, even without numbers ("They didn't have the right body armor.")
- Claims attributed to named organisations, studies, or people ("The CBO estimated this adds $2 trillion.")
- Comparative or superlative assertions ("The second biggest surplus next to Japan.")
- Short speech fragments asserting an implicit fact ("And more importantly, that was after getting a subpoena.")

Write in spoken debate style: contractions, filler words ("uh", "look,", "I mean,"), mid-sentence pivots,
references to the opponent as "he/she/my opponent/the Senator/the President". Vary sentence length:
include very short fragments (5–10 words) as well as longer rambling sentences.\
"""

SYSTEM_NO = """\
You are generating training data for a political fact-checking research project.
Generate NOT CHECKWORTHY sentences in the style of US presidential or congressional debate transcripts.

A not-checkworthy sentence does NOT make a specific falsifiable claim:
- Vague normative statements ("we need to do better", "we have to work together")
- Future intentions or promises ("I will fight for you", "we're going to fix this")
- Emotional appeals or hyperbole ("this weakens the chances of civilization to survive")
- Vague attacks without a specific claim ("he doesn't understand the impact of this")
- Rhetorical questions ("where's the plan?", "can she name one time?")
- Vague references to experts without stating what they say ("the experts are clear on this")
- General character statements, praise, or scene-setting ("I've visited communities across this country")
- Opinions and interpretations ("the African-American community has been let down")

Write in spoken debate style: contractions, filler words ("uh", "look,", "I mean,"), mid-sentence pivots,
references to the opponent as "he/she/my opponent/the Senator/the President". Vary sentence length.\
"""


def build_prompt_yes(few_shots, topic):
    lines = [f"Here are {len(few_shots)} real checkworthy sentences from political debates:\n"]
    for text in few_shots:
        lines.append(f'  "{text}"')
    lines.append(f"""
Generate exactly {BATCH_SIZE} checkworthy sentences from a debate on the topic of {topic}.
Match the style and variety of the examples — include both short and long sentences,
and avoid repeating the same structural pattern (e.g. don't make all sentences start with "According to" or all reference a vote).

Return ONLY a JSON object:
{{"sentences": [{{"text": "...", "label": "Yes"}}, ...]}}""")
    return "\n".join(lines)


def build_prompt_no(few_shots, topic):
    lines = [f"Here are {len(few_shots)} real not-checkworthy sentences from political debates:\n"]
    for text in few_shots:
        lines.append(f'  "{text}"')
    lines.append(f"""
Generate exactly {BATCH_SIZE} not-checkworthy sentences from a debate on the topic of {topic}.
Match the style and variety of the examples — opinions, vague claims, future promises, emotional appeals,
rhetorical questions. Vary length and sentence type.

Return ONLY a JSON object:
{{"sentences": [{{"text": "...", "label": "No"}}, ...]}}""")
    return "\n".join(lines)


# ── Real data loading ─────────────────────────────────────────────────────────
def load_real_data():
    df = pd.read_csv(REAL_DATA_PATH)
    yes = df[df["class_label"] == "Yes"]["Text"].dropna().tolist()
    no  = df[df["class_label"] == "No"]["Text"].dropna().tolist()
    return yes, no


def split_real_data(yes_texts, no_texts, seed=42):
    """Split into per-class few-shot pool and reference set."""
    rng = random.Random(seed)
    yes_shuf, no_shuf = yes_texts[:], no_texts[:]
    rng.shuffle(yes_shuf)
    rng.shuffle(no_shuf)
    ref_yes  = yes_shuf[:REFERENCE_N]
    pool_yes = yes_shuf[REFERENCE_N:REFERENCE_N + FEW_SHOT_REFERENCE_N]
    ref_no   = no_shuf[:REFERENCE_N]
    pool_no  = no_shuf[REFERENCE_N:REFERENCE_N + FEW_SHOT_REFERENCE_N]
    return (pool_yes, pool_no), (ref_yes, ref_no)


# ── TF-IDF vectorizer ─────────────────────────────────────────────────────────
def fit_vectorizer(all_texts):
    vect = TfidfVectorizer(ngram_range=(1, 2), max_features=20000, sublinear_tf=True)
    vect.fit(all_texts)
    return vect


# ── Filters ───────────────────────────────────────────────────────────────────
def diversity_filter(texts, keep_n, vectorizer):
    """Greedy maximin: select keep_n samples maximising minimum pairwise distance."""
    if len(texts) <= keep_n:
        return list(range(len(texts)))
    vecs = vectorizer.transform(texts)
    n = vecs.shape[0]
    selected = [random.randrange(n)]
    min_dists = np.ones(n)
    while len(selected) < keep_n:
        last = selected[-1]
        dists = 1.0 - cosine_similarity(vecs[last], vecs).flatten()
        min_dists = np.minimum(min_dists, dists)
        min_dists[selected] = -1.0
        selected.append(int(np.argmax(min_dists)))
    return selected


def distribution_filter(texts, ref_vecs, keep_n, vectorizer):
    """Keep samples with highest cosine similarity to their nearest real neighbour."""
    if len(texts) <= keep_n:
        return list(range(len(texts)))
    cand_vecs = vectorizer.transform(texts)
    nn_scores = cosine_similarity(cand_vecs, ref_vecs).max(axis=1)
    return np.argpartition(nn_scores, -keep_n)[-keep_n:].tolist()


# ── Generation ────────────────────────────────────────────────────────────────
def is_valid_batch(items, expected_label):
    """All BATCH_SIZE items must exist, be valid, and carry the expected label."""
    if not isinstance(items, list) or len(items) != BATCH_SIZE:
        return False
    for item in items:
        if not isinstance(item, dict):
            return False
        if "text" not in item or "label" not in item:
            return False
        if item["label"] != expected_label:
            return False
        text = item["text"]
        if not text or len(text) < 8 or "\n" in text:
            return False
    return True


async def generate_batch(semaphore, system_prompt, user_prompt, expected_label, topic):
    async with semaphore:
        while True:
            response = await litellm.acompletion(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": user_prompt},
                ],
                temperature=1.0,
                response_format={"type": "json_object"},
            )
            raw = response.choices[0].message.content.strip()
            try:
                parsed = json.loads(raw)
                items = parsed if isinstance(parsed, list) else (
                    parsed.get("sentences") or
                    next((v for v in parsed.values() if isinstance(v, list)), None)
                )
                if items and is_valid_batch(items, expected_label):
                    return [{"Text": it["text"], "class_label": it["label"], "topic": topic}
                            for it in items]
            except (json.JSONDecodeError, StopIteration, TypeError):
                pass


async def generate_class_candidates(n_needed, pool, label, semaphore):
    """Generate approximately n_needed candidates for a single class."""
    n_batches = max(1, -(-n_needed // BATCH_SIZE))  # ceiling division
    rng = random.Random()
    topics = random.choices(TOPICS, k=n_batches)

    system = SYSTEM_YES if label == "Yes" else SYSTEM_NO
    build_prompt = build_prompt_yes if label == "Yes" else build_prompt_no

    from tqdm import tqdm
    pbar = tqdm(total=n_batches, desc=f"  [{label}] Generating ({n_batches} batches)")

    async def tracked(topic):
        shots = rng.sample(pool, min(FEW_SHOT_N, len(pool)))
        prompt = build_prompt(shots, topic)
        result = await generate_batch(semaphore, system, prompt, label, topic)
        pbar.update(1)
        return result

    results = await asyncio.gather(*[tracked(t) for t in topics])
    pbar.close()
    return [row for batch in results if batch for row in batch]


# ── Per-class filter pipeline ─────────────────────────────────────────────────
def filter_pipeline(candidates, pool, ref_vecs, vectorizer, label, target):
    """
    Merge new candidates with the existing pool, then filter down to `target` in two steps.

    Distribution filter halves the gap between the overshooted pool and target size,
    keeping the most realistic samples. Diversity filter then selects the maximally
    spread `target` samples from what remains.
    """
    merged = pool + candidates
    if not merged:
        return []

    texts = [r["Text"] for r in merged]

    # Distribution filter: reduce from overshoot size to the midpoint between overshoot and target.
    # midpoint = target + (target × OVERSHOOT_FACTOR − target) / 2 = target × (1 + OVERSHOOT_FACTOR) / 2
    keep_n_dist = min(len(merged), round(target * (1 + OVERSHOOT_FACTOR) / 2))
    dist_idx    = distribution_filter(texts, ref_vecs, keep_n_dist, vectorizer)
    merged      = [merged[i] for i in dist_idx]
    texts       = [r["Text"] for r in merged]
    print(f"    [{label}] after distribution:  {len(merged)}")

    # Diversity filter: greedy maximin to select exactly `target` (or fewer if not enough yet).
    keep_n_div = min(target, len(merged))
    div_idx    = diversity_filter(texts, keep_n_div, vectorizer)
    merged     = [merged[i] for i in div_idx]
    print(f"    [{label}] after diversity:     {len(merged)}")

    return merged


# ── Diversity report ─────────────────────────────────────────────────────────
def report_diversity(pool_yes, pool_no, ref_yes, ref_no, vectorizer, label=""):
    def class_report(texts, ref_texts, cls):
        if len(texts) < 2:
            print(f"  [{cls}] n={len(texts)} — too few to report")
            return
        vecs = vectorizer.transform(texts)
        sims = cosine_similarity(vecs)
        np.fill_diagonal(sims, 0)
        avg_sim = float(sims.mean())

        ref_vecs  = vectorizer.transform(ref_texts)
        nn_scores = cosine_similarity(vecs, ref_vecs).max(axis=1)
        avg_nn    = float(nn_scores.mean())

        from collections import Counter
        ngrams = Counter()
        for t in texts:
            words = re.findall(r"\b\w+\b", t.lower())
            for i in range(len(words) - 1):
                ngrams[f"{words[i]} {words[i+1]}"] += 1
        top = ngrams.most_common(6)

        print(f"  [{cls}] n={len(texts)}  pairwise_sim={avg_sim:.4f}  nn_real={avg_nn:.4f}")
        print(f"         top 2-grams: {top}")

    tag = f" [{label}]" if label else ""
    print(f"\n── Diversity report{tag} ──")
    class_report([r["Text"] for r in pool_yes], ref_yes, "Yes")
    class_report([r["Text"] for r in pool_no],  ref_no,  "No")


# ── Main pipeline ─────────────────────────────────────────────────────────────
async def main(dry_run=False):
    print("Loading real data…")
    yes_texts, no_texts = load_real_data()
    (fs_yes, fs_no), (ref_yes, ref_no) = split_real_data(yes_texts, no_texts)
    print(f"  Few-shot pool: {len(fs_yes)} Yes, {len(fs_no)} No")
    print(f"  Reference set: {len(ref_yes)} Yes, {len(ref_no)} No")

    print("Fitting TF-IDF vectorizer…")
    vectorizer = fit_vectorizer(yes_texts + no_texts)
    ref_vecs_yes = vectorizer.transform(ref_yes)
    ref_vecs_no  = vectorizer.transform(ref_no)

    target_each = 15 if dry_run else TARGET_N // 2  # per class
    pool_yes: list[dict] = []
    pool_no:  list[dict] = []

    if OUTPUT_FILE.exists() and not dry_run:
        existing = pd.read_csv(OUTPUT_FILE).to_dict("records")
        pool_yes = [r for r in existing if r["class_label"] == "Yes"]
        pool_no  = [r for r in existing if r["class_label"] == "No"]
        print(f"Resuming: {len(pool_yes)} Yes, {len(pool_no)} No from {OUTPUT_FILE.name}")

    # Shared semaphore — both classes compete for the same API rate limit
    semaphore = asyncio.Semaphore(NUM_WORKERS)
    overshoot_size = round(target_each * OVERSHOOT_FACTOR)
    n_iter = 1 if dry_run else N_ITERATIONS

    for iteration in range(1, n_iter + 1):
        # Generate enough new candidates to bring pool up to overshoot_size
        n_yes = max(0, overshoot_size - len(pool_yes))
        n_no  = max(0, overshoot_size - len(pool_no))
        print(f"\n── Iteration {iteration}/{n_iter}  "
              f"(Yes {len(pool_yes)}/{target_each}, No {len(pool_no)}/{target_each}) ──")
        print(f"  Generating: {n_yes} Yes, {n_no} No new candidates "
              f"(target pool size before filter: {overshoot_size})")

        async def _empty():
            return []

        cands_yes, cands_no = await asyncio.gather(
            generate_class_candidates(n_yes, fs_yes, "Yes", semaphore) if n_yes > 0 else _empty(),
            generate_class_candidates(n_no,  fs_no,  "No",  semaphore) if n_no  > 0 else _empty(),
        )
        print(f"  Generated: {len(cands_yes)} Yes, {len(cands_no)} No candidates")

        # Filter pool + candidates down to target_each for each class
        pool_yes = filter_pipeline(cands_yes, pool_yes, ref_vecs_yes, vectorizer, "Yes", target_each)
        pool_no  = filter_pipeline(cands_no,  pool_no,  ref_vecs_no,  vectorizer, "No",  target_each)

        if not dry_run:
            all_rows = pool_yes + pool_no
            with open(OUTPUT_FILE, "w", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=["Text", "class_label", "topic"])
                writer.writeheader()
                writer.writerows(all_rows)

        report_diversity(pool_yes, pool_no, ref_yes, ref_no, vectorizer, label=f"iter{iteration}")

    print(f"\nDone. Yes={len(pool_yes)}, No={len(pool_no)}, Total={len(pool_yes)+len(pool_no)}")
    report_diversity(pool_yes, pool_no, ref_yes, ref_no, vectorizer, label="final")


if __name__ == "__main__":
    import os
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(main(dry_run=args.dry_run))
    finally:
        pending = asyncio.all_tasks(loop)
        for task in pending:
            task.cancel()
        if pending:
            loop.run_until_complete(asyncio.gather(*pending, return_exceptions=True))
        loop.close()
    os._exit(0)
